# Generated by Django 5.0.6 on 2024-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('processor', models.TextField()),
                ('price', models.IntegerField(max_length=15)),
            ],
        ),
    ]
