# Generated by Django 5.0.6 on 2024-10-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('descroptions', models.TextField()),
                ('prise', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
        ),
    ]
